-- Categorias doadas em determinado mês
SELECT COUNT(CATEGORIA.NOME) AS QTDE, CATEGORIA.NOME AS CATEGORIA
FROM TRANSACAO
JOIN ITEM ON (TRANSACAO.ITEM = ITEM.SERIAL)
JOIN CATEGORIA ON (ITEM.CATEGORIA = CATEGORIA.NOME)
WHERE
    TRANSACAO.DATA_HORA BETWEEN
        '2014-07-03 00:00:00' AND
        '2023-02-01 00:00:00'
GROUP BY CATEGORIA.NOME
ORDER BY CATEGORIA.NOME;

-- Doações para escolas com menos de 3 alunos


-- Chat de usuários de determinado post
SELECT
    C.USUARIO1 AS CRIADOR_POST, C.USUARIO2 AS MATCH, C.TEXTO AS CHAT
FROM
    CHAT C
    JOIN POST P ON P.EMAIL = C.USUARIO1;

-- USUÁRIO E SUA MAIOR AVALIAÇÃO
SELECT
    U.NOME AS NOME, MAX(A.NOTA) AS MAX
FROM
    USUARIO U
    LEFT JOIN AVALIA A ON U.EMAIL = A.USUARIO2
GROUP BY
    U.NOME;

-- Usuários avaliados por todos os colaboradores (sql nested + divisão relacional)
SELECT
    U.NOME
FROM
    USUARIO U
    JOIN AVALIA A ON (A.USUARIO1 = U.EMAIL)
WHERE NOT EXISTS (
    (
        SELECT UA.EMAIL
        FROM USUARIO UA JOIN COMUM C ON (UA.EMAIL = C.USUARIO)
        WHERE UPPER(C.FUNCAO) = 'COLABORADOR'
    )
        EXCEPT
    (
        SELECT AV.USUARIO2
        FROM AVALIA AV
        WHERE U.EMAIL = AV.USUARIO2
    )
)